export const GET_IVR_DATA = 'GET_IVR_DATA';

export const CLEAR_IVR_DATA = 'CLEAR_IVR_DATA';

export const SET_BRANDSCHEME = 'SET_BRANDSCHEME';

export const SET_CUSTOMER = 'SET_CUSTOMER';

export const LOAD_CUSTOMER_FAILURE = 'LOAD_CUSTOMER_FAILURE';

export const GET_CUSTOMERS_BY_SEARCH = 'GET_CUSTOMERS_BY_SEARCH';
