export const GET_IVR_DATA = 'GET_IVR_DATA';

export const CLEAR_IVR_DATA = 'CLEAR_IVR_DATA';

export const SET_BRANDSCHEME = 'SET_BRANDSCHEME';

export const GET_CUSTOMER_BY_ACCOUNT = 'GET_CUSTOMER_BY_ACCOUNT';

export const GET_CUSTOMERS_BY_SEARCH = 'GET_CUSTOMERS_BY_SEARCH';
